"""
Django settings for aosd project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(__file__))
PARENT_DIR = os.path.abspath(os.path.join(BASE_DIR, os.pardir))
GREATPARENT_DIR = os.path.abspath(os.path.join(PARENT_DIR, os.pardir))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '...'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


# Application definition

INSTALLED_APPS = (
    ##commented out to run without database. Production could have different needs
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #'corsheaders',
    'main',
    'aosd',
)


# ADDED THE ALLOWED HOST HERE BECAUSE PROBLEMS FOR PRODUCTION
ALLOWED_HOSTS = [
             '127.0.0.1',
             'localhost',
             '193.146.116.193',
             'miv-aodfront-01.aragon.local',
             '193.146.116.204',
             '172.27.38.119'
         ]




MIDDLEWARE_CLASSES = (
    'corsheaders.middleware.CorsMiddleware', # UNCOMENT FOR PRODUCTION 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware', # UNCOMENT FOR PRODUCTION 
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    #'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'aosd.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(PARENT_DIR, 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aosd.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'aosd',
        'USER': 'postgres',
        'PASSWORD': '',
        'HOST': 'biv-aodback-01.aragon.local',
        'PORT': 5432
    },
    'subscriptions': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'aosd_subscriptions',
        'USER': 'postgres',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': 5432
    }
}

#DATABASE_ROUTERS = ['aosd.db_routers.MainRouter']
DATABASES = {}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'es-ES'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_L10N = True

USE_TZ = False
#USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    #os.path.join(PARENT_DIR, 'static'),
    os.path.join(GREATPARENT_DIR, 'deploy2020/static'),
)

print("usando para /static/ los DIRS:", STATICFILES_DIRS)

# UNCOMENT FOR PRODUCTION START
CORS_ORIGIN_ALLOW_ALL = True

CORS_ORIGIN_WHITELIST = (
    'opendata.aragon.es',
    'preopendata.aragon.es',
    'localhost:8004',
    '127.0.0.1:8004',
    'localhost:7030',
    '127.0.1:7030',
    'miv-aodfront-01.aragon.local:7030',
    'miv-aodfront-01.aragon.local:8004',
    'miv-aodfront-01.aragon.local',
    'localhost'
)

# IE cache... (DEFAULT CORS ALLOW HEADERS + ['cache-control', 'pragma'])
CORS_ALLOW_HEADERS = (
    'x-requested-with',
    'content-type',
    'accept',
    'origin',
    'authorization',
    'x-csrftoken',
    'jwt-token',
    'cache-control',
    'pragma',
)
# UNCOMENT FOR PRODUCTION END

# 128 SECRET KEY
JWT_SECRET_KEY = ''

